### ISSUE TITLE
Cant get Minute Mode to work

### ISSUE THREAD

**Issue by DMTSource** [quantopian/zipline#1014]
I am trying to work with zipline in minute mode with third party data.I am seeing behavior where my handle_data functions is being called for every minute in my data, But the returns and benchmark are always stuck in daily mode.

# Environment

* Operating System: Started on Win 8, but moved to OSX to upgrade to Zipline 0.8.3
* Python Version: 2.7.11 :: Anaconda 2.5.0(x86_64)
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages: https://www.dropbox.com/s/n5lr5anmbxpu2km/DMT-OSX.txt?dl=0

# Description of Issue

* What did you expect to happen?
A minute mode backtest, where handle_data is being called every minute the trades and returns are occurring and logging in minute granularity.

* What happened instead?
Handle_data is being called every minute, but when I try to replace the Benchmark with minute mode data it gets ignored and new data is downloaded and then the returns and trades occur in daily mode.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Try my code or review sample output here: https://github.com/DMTSource/load-minute-data-in-local-zipline
2. The code uses the cache hack to place minute level data into the sim.
3. Notice the final lines of log, returns and benchmark are still in daily mode( only 5 items in array vs 5*390)
...

## What steps have you taken to resolve this already?
-I started by loading my data in pandas and trying to pass it to algo.run(data).
-When that didnt work I read about placing my data in the zipline dada cache to trick the yahoo loader into using my bar data in minute mode, this worked well and got handle_data to start running my minute data.
-I noticed the trading and returns only occurred 5 times(5 days in the backtest). I then tried to apply the cache hack above to the benchmark data but zipline ignores it and downloads new data.
...

# Anything else?
I am working to make this a public solution. I hope this can be useful to others as an example for minute mode backtesting:
https://github.com/DMTSource/load-minute-data-in-local-zipline
...

Thank you,

Derek.

**Comment by llllllllll** [comment]
Thank you for the report, sorry I didn't get back to you on the mailing list. I did see the post but didn't have time to dig in until today. If you are seeing your handle_data getting called minutely then the orders should be happening minutely and not at the end of the day. The result of `TradingAlgorithm.run` is `daily_stats` which is only the daily packets from the generator. We are only filtering the messages, the actual execution of those events should not be daily. We can only emit a perf packet when we have a benchmark event so if your benchmark is daily but your data source is minutely you will still be locked into a daily emission rate. If you would like to get access to each of the minute perf packets you can iterate over `algo.get_generator()` though the format is not very nice for user consumption. Unfortunatly is all changing very soon so I am not sure how much effort we want to put into cleaning up this old interface. Ideally we would move `BacktestResult` from quantopian into zipline because it is a much nicer interface to this data. Hopefully this will be addressed in the q2.0 branch.

Regarding your cache trick: I am not sure why you would swap the data our for the minute bars. You should just be able to pass the dataframe to `algo.run` and have it create the data source. In trying to set up a repro I realized we were not properly consuming the `benchmark_return_source`. I am working on a patch to address this so that you can just pass the benchmark data to `run`.

**Comment by DMTSource** [comment]
Thank you for your reply. Initially I had started with 0.7.0 when trying to pass the dataframe into run. I tried it again(now on 0.8.3) and received a new error which might suggest my format is off. I'm attempting to pass in my dataframe with format(I use the format from the yahoo file cache):
df.head(5)
                                               Open    High     Low       Close    Volume  Adj Close
2015-01-05 09:30:00+00:00  154.59  154.59  154.17  154.35     835     154.35
2015-01-05 09:31:00+00:00  154.24  154.50  154.04  154.25   10372     154.25
2015-01-05 09:32:00+00:00  154.28  154.33  154.24  154.27   10372     154.27
2015-01-05 09:33:00+00:00  154.25  154.25  153.93  153.96   19951     153.96
2015-01-05 09:34:00+00:00  153.95  154.06  153.69  153.86   29050     153.86

I get the error:
/Users/DMT/anaconda/lib/python2.7/site-packages/zipline/assets/assets.py:573: UserWarning: Missing assets for identifiers: ['Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close']
  warnings.warn("Missing assets for identifiers: %s" % missing)
Traceback (most recent call last):
  File "/Users/DMT/Dropbox (Personal)/finance/kitbot/load_minute_data_in_local_zipline083.py", line 221, in <module>
    result = algo.run(df)
  File "/Users/DMT/anaconda/lib/python2.7/site-packages/zipline/algorithm.py", line 527, in run
    source.columns, source.index[0],
  File "/Users/DMT/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 2094, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/src/properties.pyx", line 65, in pandas.lib.AxisProperty.__set__ (pandas/lib.c:42543)
  File "/Users/DMT/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 413, in _set_axis
    self._data.set_axis(axis, labels)
  File "/Users/DMT/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 2219, in set_axis
    'new values have %d elements' % (old_len, new_len))
ValueError: Length mismatch: Expected axis has 6 elements, new values have 0 elements

**Comment by llllllllll** [comment]
This is not the format for input dataframes, you need to indentify which asset that data is for. DataFrame format is date for the index and sids for the columns. The data points are the close values for the day. If you have data in this format you want to use a Panel.
