### ISSUE TITLE
Tag versioner bug

### ISSUE THREAD

**Issue by npezolano** [quantopian/zipline#1189]
Not sure how this changed but some where along the line the "v" in front of the version disappeared so the latest tags no longer show on top. See the current tags drop down menu, it shows `v0.8.3` on top when the latest is buried on the bottom as `0.9.0`. Similar issue if we run `git tag`.  Can we please keep the tag scheme consistent?

**Comment by llllllllll** [comment]
We explicitly chose to remove the `v` prefix when we switched to versioneer. This makes it so that the tag _is_ the version that it is tagging in pep440 form. This page: https://github.com/quantopian/zipline/tags appears to be sorted by time with 0.9.0 at the top. `git tag` was less ordered though:

```
(zipline3)[yui@funami zipline]$ git tag
0.8.4
0.9.0
v0.5.0
v0.5.1
v0.5.10
v0.5.2
v0.5.5
v0.5.6
v0.5.7
v0.5.8
v0.5.9
v0.6.0
v0.6.1
v0.7.0
v0.7.0rc1
v0.8.0
v0.8.3
```

Which ui is affected by this? I would prefer to keep them without the `v` but if it breaks a lot of workflows then we could change it.
