### ISSUE TITLE
Add an option to turn off benchmark/treasury updating

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#119]
So that Zipline can be run offline, i.e. so that a downloaded dataset can be used when there is no internet connection.

Without the option to disable benchmarks Zipline will currently crash on a socket exception while calling `data.loader.update_benchmarks`

**Comment by cosnis** [comment]
dose it worked for now?

**Comment by florentchandelier** [comment]
is urllib2 appropriate for zipline ? I believe the best way is not to provide an option but simply check for a connection status. Yet I would understand why urllib2 cannot be accessed from within zipline (specifically Quantopian), at which point an option is necessary ; 

At least another contributor can pass a variable from the TradingAlgorithm class down to the same location in the code in lieu of  'connection_status'. This was a quick suggestion so that I can work on few things over the next couple days without internet.

**Comment by ssanderson** [comment]
Closing this in favor of https://github.com/quantopian/zipline/issues/119.
