### ISSUE TITLE
PyCharm: zipline.api.x => Unresolved reference 'symbol' 

### ISSUE THREAD

**Issue by fredfortier** [quantopian/zipline#1205]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Mac OS El Capitain
* Python Version: 2.7.10
* Python Bitness: 64-bit
* How did you install Zipline: pip -- individually installed each library using version info in /zipline/etc/requirements.txt
* Zipline version: master

Now that you know a little about me, let me tell you about the issue I am
having:

I am using PyCharm to author my algorithms. I am able to run the simple the examples that ship with zipline. I can even analyze my results in pyfolio. As far as I can tell, zipline is installed correctly and runs happily. My problem is that I get unresolved reference errors in PyCharm for most of the zipline.api modules.

To illustrate the point, here is the contentious import statement:
from zipline.api import symbol, record, attach_pipeline, schedule_function, date_rules, \
    time_rules, order_value, order_target_percent

The PyCharm code analyzer has this to say regarding most of them:
Unresolved reference 'order_value'
Unresolved reference 'order_target_percent'

This does not prevent my algo from running. However, I am attached to the "code navigation" features of my IDE. After reviewing "api.py", I have some intuition about the cause. But I am still learning Python so I lack knowledge required to easily resolve this myself. Any suggestion would be appreciated.

Sincerely,
Frederic

**Comment by llllllllll** [comment]
Many of the functions in this namespace are dynamically added. This is because they actually resolve to bound methods of some registered `TradingAlgorithm` instance. Here is what is statically in `zipline.api`: https://github.com/quantopian/zipline/blob/master/zipline/api.py#L16 and here is the decorator's definition: https://github.com/quantopian/zipline/blob/master/zipline/utils/api_support.py#L45. Inside `TradingAlgorithm` we enter a `ZiplineAPI` context like so: https://github.com/quantopian/zipline/blob/master/zipline/algorithm.py#L406 which makes it so that all of the api methods will resolve to the currently running algorithm. For example, here is how `order` gets added: https://github.com/quantopian/zipline/blob/master/zipline/algorithm.py#L1203.

This makes it very difficult for static analysis tools to understand the module; I get the same issue with Jedi, my code completion tool. I am not totally sure what the right fix is here.

**Comment by fredfortier** [comment]
@llllllllll are you aware of any popular workaround which developers use to circumvent the limitation?

**Comment by richafrank** [comment]
@fredfortier , I'm working on a fix for you in #1208.  *Hopefully* merged and released soon.

**Comment by llllllllll** [comment]
We have added stub files which allows pycharm to know what will be in zipline.api statically.

**Comment by richafrank** [comment]
On zipline 1.0, I'm seeing the stub file installed by conda but not by pip.

**Comment by richafrank** [comment]
source dist packaging fixed in https://github.com/quantopian/zipline/commit/0cef5eff2ffebac9813d58b56b34a730510758d4
