### ISSUE TITLE
User API much too verbose and opaque

### ISSUE THREAD

**Issue by s-foley** [quantopian/zipline#1440]
Hello, user API is way too long and unwieldy. Way too many imports at top of page, each twice as long as they should be. The average length of a line of code is twice what I would like it too be. When you chain things together, you lose your train of thought. Just to take a random example off your docs:

```
set_commission(commission.PerShare(cost=0.0075, min_trade_cost=1))
set_slippage(slippage.VolumeShareSlippage(volume_limit=0.025, price_impact=0.1))
```

The first line is 66 characters! The second line is 80 characters!! You can't even indent a line so long. Isn't this why everyone hates Java???!!!

I've been forced to start writing wrappers around everything. See example below:
```
class History(object):

    def __init__(self, ticker, data):
        self.symbol = symbol(ticker)
        self.history = data.history

    def all(self, no=10, period='1d'):
        fields = ['open', 'high', 'low', 'close', 'volume']
        return self.history(self.symbol, fields, no, period)

    def __getattr__(self, field, no=10, period='1d'):
        return self.history(self.symbol, field, no, period)
 
class Stock(object):

    def __init__(self, ticker, data):
        self.symbol = symbol(ticker)
        self.current = data.current
        self.history = History(ticker, data)

    def all(self):
        fields = ['price', 'last_traded', 'open', 'high',
                  'low', 'close', 'volume']
        return self.current(self.symbol, fields)

    def __getattr__(self, field):
        return self.current(self.symbol, field)`
```

```
aapl = Stock('aapl', data)
aapl.close
aapl.all()
aapl.history.close
aapl.history.all()
```

It would be really good if you guys focus on short code lines and tying everything together that fits together so there isn't multiple imports and 80 character lines of code. Clean code allows one to think though problems much better.

Thanks!

**Comment by ssanderson** [comment]
@s-foley do you have concrete suggestions for how you'd like to see the set_commission and set_slippage APIs improved?  If you're concerned about line length, you could re-write the lines you quoted above as:

```
com_model = PerShare(cost=0.0075, min_trade_cost=1)
set_commission(com_model)

slip_model = VolumeShareSlippage(volume_limit=0.025, price_impact=0.1)
set_slippage(slip_model)
```

With regard to your proposed history changes, there are some challenges with doing

If that's still too much, you could shorten further:
```
c = PerShare(0.0075, 1)
set_commission(c)

s = VolumeShareSlippage(0.025, 0.1)
set_slippage(s)
```

I'd argue that the last example is made worse by removing the keyword arguments, since it's no longer clear to a reader what the parameters mean, but if that's clearer for you, then the beauty of Python is that you have a variety of stylistic choices available to you.

With regard to your proposed history changes, one issue you'll run into with a strategy of wrapping specific assets objects is that assets can change tickers over time, and they can be created or destroyed in the middle of a simulation.

In general, Zipline tries allow algorithms to work even on historical datasets that include information about ticker changes and asset creation/destruction.  This means that we tend to discourage referring to specific stocks in the text of an algorithm, since doing so renders the algorithm broken if that stock stops existing or changes name.

You're more than welcome to continue using your wrappers if you find them more convenient, but it's unlikely that we'll incorporate them directly in zipline.

**Comment by s-foley** [comment]
Hello and thanks for the reply. I was a bit frustrated when I wrote the
above after spending a few hours trying to get things working, so I would
like to clarify and say I really like zipline and think it's a great
resource.

Your second example is beautiful. That is just how I like to code...short
and having only one or two things happening per line. I find that too much
chaining:

val = obj.obj.attr['key'].attr

leads to code I can't understand the next week. In terms of coding style, I
am using numpy and pandas a lot and think those are both good models for
API design. In my perfect world, you would have only one import:

import zipline as zl

and have everything flow from there. What I would like most is easy access
to data structures.

account = zl.account()
portfolio = zl.portfolio()
stock = zl.stock('aapl')

and then, for each, easy access to methods and attributes:

trade = stock.order(10)
trade.profit()
trade.sell('all')

stuff like that. Basically, less imports, shorter code lines, direct access
to data structures, less chaining.

Anyway, my thoughts as a user. Maybe things you can think about for the
future. I do like your pipeline concept.
