### ISSUE TITLE
Cannot import history

### ISSUE THREAD

**Issue by apb210** [quantopian/zipline#1628]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10
* Python Version: `$ python --2.7.1`
* How did you install Zipline: conda

Using the Eclipse IDE, the import 

from zipline.api import history does not work

Sincerely,
Apratim

**Comment by FreddieV4** [comment]
Hi @apb210 thanks for opening the issue. I'm not familiar with Eclipse as a Python IDE but I'm guessing that you're using PyDev? If so, you might have to check that the environments of Python and PyDev are synced up properly. 

You can do this by going to `Preferences -> PyDev -> Interpreter` and clicking an option that says something about synchronizing the environments.

Otherwise, I haven't seen this issue as I'm not familiar with Eclipse as a Python IDE.

Can you try and run `from zipline.api import history` in a non-Eclipse interpreter? If you just type `python` in your command prompt it should pull up an interpreter where you can test this.

**Comment by FreddieV4** [comment]
@apb210 `history()` commands are deprecated, so if you're using the latest zipline or zipline `1.0.2` you should make calls to `data.history()`.

Feel free to re-open this if you come across this issue again.
