### ISSUE TITLE
Consider shortening Asset.__repr__?

### ISSUE THREAD

**Issue by ssanderson** [quantopian/zipline#1675]
The repr for asset currently displays all the information that can be associated with an asset, and the verbosity makes it unpleasant to use, especially in collections where the default behavior is to repr the elements of the collection.  For example, this is what a list of 5 assets from the Q database currently looks like:

```
In [7]: assets[:5]
Out[7]:
[Equity(2, symbol=u'ARNC', asset_name=u'ARCONIC INC', exchange=u'NYSE', start_date=Timestamp('2002-01-01 00:00:00+0000', tz='UTC'), end_date=Timestamp('2017-02-02 00:00:00+0000', tz='UTC'), first_traded=None, auto_close_date=Timestamp('2017-02-07 00:00:00+0000', tz='UTC'), exchange_full=u'NEW YORK STOCK EXCHANGE'),
 Equity(6, symbol=u'AACE', asset_name=u'ACE CASH EXPRESS INC', exchange=u'NASDAQ', start_date=Timestamp('2002-01-01 00:00:00+0000', tz='UTC'), end_date=Timestamp('2006-10-05 00:00:00+0000', tz='UTC'), first_traded=None, auto_close_date=Timestamp('2006-10-10 00:00:00+0000', tz='UTC'), exchange_full=u'NASDAQ GLOBAL SELECT MARKET'),
 Equity(14, symbol=u'AALA', asset_name=u'AMERALIA INC', exchange=u'NASDAQ', start_date=Timestamp('2002-01-01 00:00:00+0000', tz='UTC'), end_date=Timestamp('2006-03-30 00:00:00+0000', tz='UTC'), first_traded=None, auto_close_date=Timestamp('2006-04-04 00:00:00+0000', tz='UTC'), exchange_full=u'NASDAQ GLOBAL MARKET'),
 Equity(21, symbol=u'AAME', asset_name=u'ATLANTIC AMERICAN CORP', exchange=u'NASDAQ', start_date=Timestamp('2002-01-01 00:00:00+0000', tz='UTC'), end_date=Timestamp('2017-02-02 00:00:00+0000', tz='UTC'), first_traded=None, auto_close_date=Timestamp('2017-02-07 00:00:00+0000', tz='UTC'), exchange_full=u'NASDAQ GLOBAL MARKET'),
 Equity(24, symbol=u'AAPL', asset_name=u'APPLE INC', exchange=u'NASDAQ', start_date=Timestamp('2002-01-01 00:00:00+0000', tz='UTC'), end_date=Timestamp('2017-02-02 00:00:00+0000', tz='UTC'), first_traded=None, auto_close_date=Timestamp('2017-02-07 00:00:00+0000', tz='UTC'), exchange_full=u'NASDAQ GLOBAL SELECT MARKET')]
```

By comparison, the current `__str__` is relatively compact:

```
In [8]: map(str, assets[:5])
Out[8]:
['Equity(2 [ARNC])',
 'Equity(6 [AACE])',
 'Equity(14 [AALA])',
 'Equity(21 [AAME])',
 'Equity(24 [AAPL])']
```

While it's occasionally nice to have all the repr information available, I think those cases are outweighed by the need to do processing to generate readable error messages any time an asset might appear in a structure.

Since the asset repr is a major part of Zipline/Quantopian's UI, I'd like to invite some discussion on whether/how the Asset repr should be changed.  Some questions:

1. Do other people agree that the asset repr is too verbose?
2. If repr is too verbose, how should we shorten it?  Do we want to reduce it all the way down to what `__str__` currently shows, or is there a middle ground between `__str__` and the current `__repr__`?  The non-sid fields I use most often are, in order:
    - symbol
    - start/end date
    - asset_name  # Significant dropoff from start/end
    - exchange
    - auto_close_date  # Significant dropoff from exchange.
3. If we want to truncate Asset repr, should we provide an option (ala `pd.set_option`) to restore the verbose repr and/or set a custom repr?  Something like this might be useful for PyFolio/Alphalens where visual space is at a premium.

cc @twiecki @gusgordon @llllllllll @ehebert @richafrank @mtydykov @kglowinski @dmichalowicz @jmccorriston @jbredeche @ahgnaw for feedback

**Comment by ehebert** [comment]
:+1: on shortening.
Your order seems right for `Equity` instances.
For `Future` instances, I would rank `auto_close_date` the same as `start_date` and `end_date`.

**Comment by dmichalowicz** [comment]
Agree with Eddie, I look at `auto_close_date` frequently for futures.

**Comment by mtydykov** [comment]
Agree about shortening. I also like the idea in (3) of optionally allowing the repr to be more verbose.

**Comment by jmccorriston** [comment]
I agree with Eddie and David. Your list is spot on for equities, but for futures, auto_close_date should be in the same tier as start/end date. My vote would be to just have a simplified version that matches what `__str__` shows. In my own experience, if I want to see the start/end date, I explicitly ask for the relevant attribute. I do this because the verbosity makes it too hard to read, or my log line gets truncated on Q. Obviously, if we only cut down to a subset, this would change at least a little bit, but I think that the most common use case here would be someone just trying to identify an asset, which can be done with `(sid [SYMB])`. 

I'm not against the option to restore verbosity, but I think the value would be pretty limited in the community.

**Comment by gusgordon** [comment]
Makes sense to me.

Relatedly, it might be worth it to have something that's even less verbose than `__str__`. Consider pyfolio, where we are displaying asset names all the time. Using `__str__` is too verbose (we already know it's an `Equity`!), and `symbol` can sometimes lead to confusion if there are multiple assets with the same symbol. We've elected to use a symbol-sid convention, e.g. `AAPL-24`. The ideal solution in pyfolio's case is probably to only include the sid if there is symbol overlap, otherwise only the symbol needs to be displayed.

**Comment by ssanderson** [comment]
> we already know it's an Equity!

What happens when someone wants to analyze a futures (or, especially, a mixed-asset algorithm) with pyfolio?  symbol-sid is still sufficiently distinguishing here, of course, but I wouldn't advise baking in the assumption of a single asset type in pyfolio's display formatting.

**Comment by gusgordon** [comment]
True, though most people will probably trade primarily one asset type in their strategy. If someone is looking at a long list of assets they've traded, they don't need the type displayed unless there could be some uncertainty about the properties of the asset. Of course it's also nice to have a uniform format, so there are tradeoffs.

**Comment by jmccorriston** [comment]
We're going to need to make some pyfolio updates when futures roll through ;)

**Comment by ssanderson** [comment]
@jbredeche expressed frustration in slack today that this has not yet been done.

**Comment by FreddieV4** [comment]
@ssanderson in what case would we worry about not having a more verbose repr? 

I think shortening it, making it similar to `__str__` would be useful. While working on the `Transaction` repr change I was looking at `Asset` as an example and thought it had too much information.

**Comment by ssanderson** [comment]
@FreddieV4 I do find it occasionally useful to have all the info at hand.  I think those cases are outweighed, however, by the cases where the repr is too verbose.

At this point I think just changing `__repr__` to match the current `__str__` is a strict improvement that's worth doing.  In the future, we can add hooks for contexts like PyFolio that might want to contextually-override the repr, but I think bikeshedding on that design isn't worth the opportunity cost of not improving the repr now.

Want to put together a PR for making `__repr__` match `__str__`?  I think the easiest way to do that is to just rename the current `__str__` to `__repr__`, and delete the current `__str__` implementation (`__str__` defaults to `__repr__` if no explicit `__str__` is defined).

**Comment by FreddieV4** [comment]
@ssanderson Sure I can put together a PR for this.

**Comment by FreddieV4** [comment]
@ssanderson Sure I can put together a PR for this.

How does the `__repr__` works between `Asset` and `Equity` though? In the `Equity` object we define the repr and it's pretty much the same as the repr for `Asset`. Would the repr for `Equity` not override the repr for `Asset` because it's a subclass?

i.e. Wouldn't I have to change the repr for both `Asset` and `Equity`?

**Comment by FreddieV4** [comment]
In the latest release so going to close this. Feel free to re-open for any extended discussion on this 🙂
