### ISSUE TITLE
orders shifted

### ISSUE THREAD

**Issue by ikfdarba** [quantopian/zipline#1844]
I am running a daily simulation on data i uploaded to zipline.

I am issuing an order on a specific date which i read through a feed file, however the orders i am issuing are being placed 2 days after i issue them (ie the first return computation is performed 2 days later).

For example i issue an order on the 18th of august 2015.

And i can see in the log file that the order is being issued on the 18th.

![image](https://user-images.githubusercontent.com/25511217/27184758-be602f54-51eb-11e7-94b9-dcf0520ef291.png)

When i look at the transactions however:
```
perf.transactions
Out[806]: 
2015-08-18 20:00:00                                                   []
2015-08-19 20:00:00    [{'price': 66.589, 'commission': None, 'dt': 2...
2015-08-20 20:00:00                                                   []
2015-08-21 20:00:00                                                   []
Name: transactions, dtype: object
```

The price shown in the transaction is the closing price on the 19th

When i check the daily returns im getting this:
```
perf.returns
Out[810]: 
2015-08-18 20:00:00    0.000000e+00
2015-08-19 20:00:00   -1.000000e-07
2015-08-20 20:00:00   -2.799948e-03
2015-08-21 20:00:00   -3.489899e-03
Name: returns, dtype: float64
```

the first non zero return (-2.799948e-03) on the 20th is the return for the closing of the 19th to the closing of the 20th (ie the return from the closing 19th to the closing 20th).

There is no slippage and no commissions
```
set_slippage(slippage.FixedSlippage(spread=0.0))
set_commission(commission.PerShare(cost=0))
```

**Comment by ernestoeperez88** [comment]
Hello @ikfdarba, thanks for posting this question. There are a couple of concepts that explain the results you are getting: 

* Order execution - When your algorithm places an order on a given bar, the order begins filling on until the next bar (regardless of the slippage model used). This way, the backtester guards your algorithm against lookahead bias. 

In the example you shared, the logs show an order is placed on August 18th 2015. The transaction is then recorded on the next bar (August 19th 2015), which is when the order gets filled. This is consistent with the way Zipline handles order execution. 

* Returns - Algorithm returns are calculated as pnl / (total capital at start of period) (you can find the corresponding calculation [here](https://github.com/quantopian/zipline/blob/8322423dc86415106543409794ae80f6dbf852e9/zipline/finance/performance/period.py#L316)). This means that the very first time your algorithm shows returns the calculation will be (pnl for the day) / (starting capital).

Assuming you used the default starting capital ($10,000,000), the perf.returns you shared show the algorithm actually had a loss of $1 on 2015-08-19, after order mentioned above got filled.

**Comment by frosk1** [comment]
is there a way of filling an order at the same day(same bar) it was placed?

**Comment by HereticSK** [comment]
Admittedly, filling order on the next bar helps preventing look ahead bias. However, that makes some algorithm much more complicated. 

For example, in some markets, trading suspension happens frequently. Under the current mechanism, if an order is placed on the current bar, but the corresponding stock becomes suspended on the next bar, the order will fail unexpecetedly. 

This can be easily avoided by filtering suspended stocks from the universe before placing an order on a given bar if `instant_fill` is allowed. And it is safe because the suspension status of a stock is usually available before the market opens.

Without `instant_fill`, implementing universe filtering becomes much more complicated. This is because the trading status infomation belongs to the next bar, so the user has to look at _the next bar_ to check whehter a stock is tradable, but `handle_data(context, data)` is intended to focus on _the current bar_. This separation makes it less intuitive to write a strategy.

I think `instant_fill` is helpful especially for periodically rebalancing strategies like multifactor and event-driven, since they don't much depend on signals based on market data. It would provide more flexibility.

**Comment by frosk1** [comment]
The argument concerning the look ahead bias makes no sense if trading closing prices with an underlying data/bundle which consists only on daily bars. There has to be a mechanism to trade the current closing price of the current day.

Scenario: My data bundle only consists of daily price data, so no minute bars. The next bar is always the closing of the next day. I am facing the closing of todays stock and want to place an order on that specific closing price. This is realsitic an can be done in life trading scenario.

**Comment by frosk1** [comment]
Concerning the look ahead bias: After the closing price is official, there is time left to trade with this closing price. After Hours Trading !

**Comment by ayxemma** [comment]
is the issue solved and is there a way to make sure trade executed same day?

**Comment by a-camuto** [comment]
is there any way we could reintroduce the `instant_fill` flag ?

**Comment by ernestoeperez88** [comment]
One way to simulate instant fills is to create a [custom slippage model](https://github.com/quantopian/zipline/blob/master/zipline/finance/slippage.py#L83) that uses the previous bar's close price (or current bar's open price, instead of close) to fill incoming orders. Here is an example:

```
# Custom slippage model
class InstantSlippage(SlippageModel):
    
    def process_order(self, data, order):
        # Use price from previous bar
        price = data.history(order.sid, 'price', 2, '1d')[0]
        
        # Alternative: Use current bar's open, instead of close
        # price = data.current(order.sid, 'open')

        return (price, order.amount)
```

To use this slippage model, you would need to include `set_slippage(InstantSlippage())` in your algorithm's `initialize` function. Keep in mind that orders would still begin filling on the next bar.


@frosk1 : Zipline does not support after-hours trading. I agree that running simulations with day frequency data exacerbates the difference between the price at which you place a trade, and the price at which that trade fills. However, using the closing price of the current bar to fill an order placed on that same bar does introduce look-ahead bias. Think about it this way: your algorithm uses the current bar's price for calculations, and then places an order. If the order were to fill at that same price, it would be as if your algorithm knew the fill price beforehand and incorporated that information on its calculations. This would introduce unrealistic performance in your simulations.

@a-camuto : If you would like to track `instant_fill` as a feature request, please open a new issue.

I am closing this issue since the original question has been addressed.
