### ISSUE TITLE
Add Indian Stock Exchanges Calendar

### ISSUE THREAD

**Issue by mr-karan** [quantopian/zipline#1923]
Dear Zipline Maintainers,

As mentioned [here](https://gitter.im/quantopian/zipline?at=5999c994162adb6d2e171d31), it would be great if we can add support for Indian stock exchanges like NSE, BSE, MCX to [zipline.utils.calendars](https://github.com/quantopian/zipline/tree/e1b27c45ae4b881e5416a5c50e8945232527ea59/zipline/utils/calendars)

I'd like to be assigned for this task, if maintainers agree on this.

Sincerely,
Karan

**Comment by FreddieV4** [comment]
Hi @mr-karan I can't think of a reason right now not to have more calendars. I'm finishing up PR #1800 so that people can actually use those calendars, so just a heads-up.

If you take a look at the [Trading Calendar API](http://www.zipline.io/appendix.html#trading-calendar-api) you could work on making a new calendar.

**Comment by freddiev4** [comment]
Hi @mr-karan you should be able to make your own calendar (merged that PR above) and use that as long as you have data with timestamps that match up to that trading calendar (you'd have to make your own custom bundle it seems). 

Going to close this but feel free to re-open if you have any other issues, and feel free to share calendar if you decide to work on it 🙂

**Comment by freddiev4** [comment]
Closing this as we have this capability in the latest release of zipline. Feel free to update to 1.2.0 with either:

```
pip install -U zipline
```

or

```
conda update zipline -c quantopian
```
