### ISSUE TITLE
Incorrect sortino ratio

### ISSUE THREAD

**Issue by jSumne** [quantopian/zipline#2159]
When running zipline with a capital base of 100000 with this algorithm
https://pastebin.com/CNVbw29Q

It gives a capital of -80000 and a sortino ratio of 102.3967 

This obviously is an incorrect sortino ratio but I don't understand how it is calculating it at 102.

**Comment by jbredeche** [comment]
Hi @jSumne , thanks for the report, and sorry for the (very) slow response.

From what I can tell, your algorithm is incurring extremely high leverage because each minute, you might be ordering $10,000 worth of AAPL (lines 21-22), and you're also consistently selling $10,000 worth of AAPL every minute (lines 23-24). I ran your backtest on the Quantopian platform, from 2011-01-04 to 2011-01-07, with $100k capital. I ended up with 13028.56x leverage.

Risk metrics can grow to extremely high numbers that might look 'incorrect'. However, I believe the root issue here is that the algorithm's leverage is growing much higher than you'd expect.

In case this is useful, our sortino ratio is done in the Empyrical library: https://github.com/quantopian/empyrical/blob/master/empyrical/stats.py#L727

I'm going to close this issue for now, but definitely let us know if you see any more issues with the sortino ratio.
