### ISSUE TITLE
Minute data not working

### ISSUE THREAD

**Issue by AdeBijon** [quantopian/zipline#2264]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment
windows 10 64-bit
<details>

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
First of all let me say That I am new here on zipline so I don't really know what is the proper way to formulate my questions.

Having said that I wanted to get some minute history data by using the following:
`
hist_minutes = data.history(context.aapl,'open',50,'1m')
`

This gave me the following error:
`NoDataForSid: No minute data for sid 2509.`

This is strange because when I used 1d instead of 1m it did work, so why is that? And how can fix this in order to also get minute data.

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

# Anything else?

...

Sincerely,
Ade

**Comment by freddiev4** [comment]
Hi @AdeBijon. Assuming you ingested the [Quandl bundle](http://www.zipline.io/bundles.html#default-data-bundles) (because your post doesn't say otherwise), that dataset in particular only has daily prices, and does not have minutely prices. You'll need to gather your own minutely data and either [write a new bundle](http://www.zipline.io/bundles.html#writing-a-new-bundle) or [ingest csv files](http://www.zipline.io/bundles.html#ingesting-data-from-csv-files).

**Comment by freddiev4** [comment]
Going to close this as no follow up from OP; feel free to reopen if you still have issues 🙂
