### ISSUE TITLE
Clean zipline install failing

### ISSUE THREAD

**Issue by marketneutral** [quantopian/zipline#2270]
Hi, I am having trouble with a clean zipline install:

```
conda clean --all
conda create -n py27 python=2.7 anaconda
conda activate py27
pip install zipline --no-cache-dir
```

`pip freeze` gives

```
alembic==1.0.0
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2018.4.16
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cyordereddict==1.0.0
Cython==0.28.5
decorator==4.3.0
empyrical==0.5.0
idna==2.7
intervaltree==2.1.0
Logbook==1.4.0
lru-dict==1.1.6
lxml==4.2.4
Mako==1.0.7
MarkupSafe==1.0
multipledispatch==0.6.0
networkx==1.11
numexpr==2.6.6
numpy==1.15.0
pandas==0.22.0
pandas-datareader==0.6.0
patsy==0.5.0
python-dateutil==2.7.3
python-editor==1.0.3
pytz==2018.5
requests==2.19.1
requests-file==1.4.3
requests-ftp==0.3.1
scipy==1.1.0
six==1.11.0
sortedcontainers==2.0.4
SQLAlchemy==1.2.10
statsmodels==0.9.0
tables==3.4.4
toolz==0.9.0
trading-calendars==1.1.0
urllib3==1.23
wrapt==1.10.11
zipline==1.3.0
```

And then a `zipline --help` gives many errors all of the flavor

```
/anaconda3/envs/py27/lib/python2.7/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning:
numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
```

One observation is that pip is pulling the versions of numpy and pandas associated with the `latest` build, not the `stable` build of zipline.

Thanks,
Jonathan

**Comment by richafrank** [comment]
Hey @marketneutral - This is an unfortunate and common problem with our (and others') binary dependency on numpy. When pip installs zipline and compiles its c extensions, the environment needs to have the intended version of numpy already installed. The workaround is to first install numpy (at the version you want) and then zipline. I have a [PR](https://github.com/quantopian/zipline/pull/2020/files#diff-a2e1e3b391e0e24fcd7e517d40d9bba8R26) to improve the install docs, but it hasn't been merged yet. 

If you still see issues, then probably you're installing the zipline wheel you compiled earlier against another numpy, so, as you have, `--no-cache-dir` or `--no-binary` may be helpful.

For what it's worth, conda handles this particular dependency more robustly than pip, in that the zipline package is tied to the numpy package that will be installed.

**Comment by ssanderson** [comment]
@marketneutral that error means that you've got a version of pandas that's compiled against a different version of numpy than what you have installed. The most common way that that happens is that you install the compiled [wheel](https://wheel.readthedocs.io/en/stable/) that the pandas team built when they released a particular version (in this case, 0.22) alongside a more recent version of numpy. 

For example, if you run the following invocation:

```
pip install numpy pandas==0.22
```

pip will install the latest version of numpy plus pandas 0.22, and by default pip will use the wheel for pandas 0.22. Pip defaults to using wheels because it makes the install step much faster (because there's no compile step), and it means that as a user you don't have to set up a C compiler toolchain (which is hard for many users, especially on windows). Unfortunately, using the pandas wheel in this case results in a broken install, because PyPI doesn't allow you to upload multiple compiled wheels for the same OS (and even if it did, it doesn't have enough fine-grained dependency information to know that the pandas 0.22 wheel should only be used with the version of numpy that was released as of that time).

There are a couple ways you can fix this issue:

1. Use conda to install zipline. It looks like you're already using conda to manage your environment, and the primary advantage of conda over pip is that it natively understands this kind of binary incompatbility issue (and in particular, it has a bunch of special-case support for numpy). We've released zipline 1.3.0 on the quantopian conda channel, so the instructions in http://www.zipline.io/install.html#managing-conda-environments should work AFAIK.
2. Pass `--no-binary :all:` when installing zipline with pip. This will make the install take longer, because it will download an "sdist" (source distribution) and compile all your packages from source, but it avoids the "wheel compiled against the wrong version of a dependency" issue because you're re-building all your packages locally. Doing this might require you to install some additional dependencies to make the build work (in particular, you'll need a working compiler toolchain for C and Fortran, which you would get from something like [homebrew](https://brew.sh/) on OSX or [apt](https://wiki.debian.org/Apt) on Debian-based linux.
3. Pre-install known-compatible versions of numpy and pandas before installing zipline. It looks like we're currently running our "recent numpy/pandas" CI builds on [pandas 0.22.0 and numpy 1.14.1](https://github.com/quantopian/zipline/blob/master/.travis.yml#L49), so that's probably a good place to start. It's probably a good idea to pre-install at least numpy no matter what, because of all the packages that depend on it and the number of interesting ways you can end up with a broken build from compiling them against the wrong version of numpy. We've seen this cause enough trouble that @richafrank has an [open PR](https://github.com/quantopian/zipline/pull/2020/files) that just makes it an error to try to install Zipline without already having a valid numpy. We should probably just merge that PR :).

**Comment by ssanderson** [comment]
@richafrank jinx!

**Comment by marketneutral** [comment]
Got it! Thank you @richafrank and @ssanderson!
