### ISSUE TITLE
Local installation of pip packages

### ISSUE THREAD

**Issue by willianpaixao** [quantopian/zipline#2281]
Hi Zipline maintainers!

I was trying to locally build and install Zipline from Git in my machine.
The documentation is really great, very well explained.

It was easy to download, build but it was lacking instructions on how to install the package.
Half an hour later I found in a forum that a `python setup.py install`do the job.
It's quite obvious and even a bit stupid that this is the first thing to try, but would be nice to add that to the documentation (http://www.zipline.io/development-guidelines.html).

Kind regards,
--
Willian Paixao

**Comment by ssanderson** [comment]
Hi @willianpaixao. Thanks for the suggestion. FYI, if you're doing local development on zipline, you probably want `pip install /path/to/zipline/checkout/` rather than `python setup.py install`. Installing with pip rather than invoking setup.py is usually preferable because it makes it easier to uninstall packages. c.f. [this StackOverflow post](https://stackoverflow.com/questions/15724093/difference-between-python-setup-py-install-and-pip-install) for details on this.

I'm not sure when someone from the zipline team will have a chance to look into updating this, but if you'd like to take a crack at it, you can find the source for that page at https://github.com/quantopian/zipline/blob/master/docs/source/development-guidelines.rst.

**Comment by willianpaixao** [comment]
@ssanderson done. Could you please review it?
