### ISSUE TITLE
Symbol lookup for global markets

### ISSUE THREAD

**Issue by willianpaixao** [quantopian/zipline#2583]
Dear Zipline Maintainers,

It's common knowledge that the `quantopian.research.symbols()` only works for the US markets.

In a recent post, Dan Whitnable explained the reasons why the feature of global lookups wasn't implemented just yet. [[1]](https://www.quantopian.com/posts/identifying-the-ticker-symbols-for-global-equity-indian-market)

And yes, I know that we can still partially retrieve some information following [these instructions](https://www.quantopian.com/posts/use-staticassets-for-equities-in-foreign-markets).

And still, would be a great feature to have symbol lookup for other markets, maybe starting with Exchanges that still follows the same naming conventions. What can we do to help on that?

Kind regards,
Willian Paixao

**Comment by willianpaixao** [comment]
@ssanderson any feedback on this issue?

**Comment by ssanderson** [comment]
hey @willianpaixao . Most of the code for `quantopian.research.symbols` isn't open source, so I don't think there's much to be done in zipline about this. Ultimately, calls to `symbols` are handled by a `AssetFinder.lookup_generic`, which already takes a `country_code` parameter. The resolution for this issue would likely need to be made in the Quantopian codebase, and would mostly involve threading down a `country_code` parameter from `symbols` to the call to the AssetFinder call.

I'm going to close this issue since I don't think there's anything to be done in Zipline for this request, but I can post this internally to remind people that there's still interest in this feature.

To confirm what you're looking for, would adding a `country_code` parameter to `symbols` (most likely with a default value of `'US'` for backwards compatibility) be sufficient for your use-case?
