### ISSUE TITLE
Is it really required to change the source code to load csv files as bundles

### ISSUE THREAD

**Issue by leoniloris** [quantopian/zipline#2657]
https://www.zipline.io/bundles.html#ingesting-data-from-csv-files
Is it really required to change the source code to load csv files as bundles? this seems absurdly wrong.

I'm tying to do this through a python script but it does not seem to work

**Comment by RichardDale** [comment]
No it's not required.  

The documentation references a file:
~/.zipline/extension.py

which is outside of the source folder - i.e. in your user folder and meant to be edited.

Cheers,
Richard.

**Comment by leoniloris** [comment]
Still, it's not good to change any source code in any occasion.  A better approach would be to have a function doing that

**Comment by llllllllll** [comment]
If you would like to ingest data without updating your extension.py, you can use the pre-registered `csvdir` bundle. For example:

```
$ CSVDIR=/path/to/your/csvs/ zipline ingest -b csvdir
```

There are a few downsides to using the built in csvdir bundle over registering a custom bundle. The first is that you must always remember to set the same value for `CSVDIR`. This must be set every time you run an ingest. This can be solved by setting the variable in your `~/.bash_profile`. The second issue is that you cannot have multiple csvdir bundles if you just use the default `csvdir` bundle. This would be useful if you had multiple data sources and wanted to compare your results for the same algorithms against many data feeds. This is not a common use case, so it may not be an issue for you.

One note about the extension.py: ~/.zipline/extension.py is not part of zipline and is not the source code for zipline. This file exists so that users can customize zipline _without_ requiring them to modify the source of zipline itself. You should think of this file like configuration. The reason it is Python and not json or something simple is that users can configure behavior, specified with Python code, as well as simple values. While zipline can be used as a library, it may also be used as a command line application. When being used as an application, users need a location where they can register code for things like bundles or custom risk metrics.
