### ISSUE TITLE
how to realize a custom factor whose algo use its own history data

### ISSUE THREAD

**Issue by zhangzheng88** [quantopian/zipline#2663]
suppose the algo is:
x_n = max (x_(n-1) + p)
   x_n: the factor value at day n
   x_(n-1): the factor value at day n-1
   p: some other value at day n

I found the CustomFactor can't use it's own as inputs.

thank you.

**Comment by ssanderson** [comment]
There's currently no way to write a CustomFactor that depends on its outputs from a previous day, and that's by design.

There are two important reasons for this design choice:

1. A factor that depends on its previous day's output needs some form of "base case" for the first days it runs. But if you have special handling for the first day, then that usually means that you'll get different results depending on the time range that you run your pipeline over, which means there's no well-defined answer for "what's the value of this factor on this day?".
2. CustomFactors receive data that's adjusted as of the date that the factor is evaluated. This means that when a corporate action like a split happens, the data that's fed into the factor can be substantially different from the previous day's data. Most incrementally updating computations of the kind you're describing wouldn't handle an event like a split correctly.
