### ISSUE TITLE
how the quantopian algorithm IDE identify the timezone?

### ISSUE THREAD

**Issue by zhangzheng88** [quantopian/zipline#2667]
i was using the quantopian's algorithm IDE. and confused with the time shows at logs and transactions.

since i was in china, the timezone in logs and transactions is CST(China Standard Time). My questions are:
1 how the algorithm IDE identify the timezone?
2 Is there a way to set the timezone for logs and transactions.

![image](https://user-images.githubusercontent.com/17842829/76611880-2a549300-6556-11ea-8fa0-e2d649ebb5a9.png)
![image](https://user-images.githubusercontent.com/17842829/76611923-3e989000-6556-11ea-87f4-749113f5a366.png)

thank you

**Comment by richafrank** [comment]
Hi @zhangzheng88 , Thanks for the question. 

It looks like your question was [answered](https://www.quantopian.com/posts/how-the-algorithm-identify-the-timezone) on the Quantopian forums! If you want to know more about it, I'd definitely follow up there, since the question is about the Quantopian platform, as opposed to zipline.
