### ISSUE TITLE
history() for opening price

### ISSUE THREAD

**Issue by heyuhere** [quantopian/zipline#374]
First, thank you for open-sourcing this nice library. Question about history(). It does not seem to support 'open_price' as field. When it is passed, it throws KeyError. For 'open', I get just the last value for a given period, leaving the rest as NaN.

I wonder if this behavior is expected. If so, do you have a plan to support open_price like the other fields?

**Comment by anddam** [comment]
@ssanderson about [this comment](https://github.com/quantopian/zipline/issues/374#issuecomment-49533563) why not provide past history if it's available in datasource?

Are there any plan to level this on par with Quantopian where the past data is available even on first handle_data execution? I.e. is it implemented this way in zipline on purpose or has it just not been worked on yet?

This would make easier to port an algorithm from zipline to Quantopian since there's no need to prefill data.

**Comment by DMTSource** [comment]
Is there a work around for this? I am working locally with zipline to optimize variables for my trading algos but I cannot get the open_price, or close_price of the SPY symbol when working with history(). I need the entire bar to recreate my work from Quantopian.

**Comment by llllllllll** [comment]
@DMTSource, there is not currently a workaround other than warming up your algorithm by setting the start date to the beginning of your history window and skipping 1 history window worth of bars before executing your algorithm. Just a note, this will only work if you pre-declare your history spec with an `add_history` call. @anddam , This is something that we agree would be nice, and you are correct that this data should be available to backfill your history container; however, we have not had time to add this feature.

**Comment by llllllllll** [comment]
We are tracking the backfill feature in #956
