### ISSUE TITLE
len(context.portfolio.positions) increases by 1 every time you check for a nonexistent position

### ISSUE THREAD

**Issue by seongsean** [quantopian/zipline#467]
Context.portfolio.positions will add on an extra position with `amount = 0` every time you check for a position that doesn't exist. 

E.g. if you don't own and have never owned SPY in your current algorithm but try context.portfolio.positions['SPY'], the next time you look at context.portfolio.positions, it will have SPY in there with amount = 0

Why this matters:

This becomes an issue when a zipline user is using context.portfolio.positions to check for all the securities he's ever owned. E.g. have I ever owned SPY? This might falsely lead the user to think that he's owned SPY when really, all he's done is if context.portfolio.positions[SPY] != None or something similar

It seems that the `__missing__` hook here does that

```
class Positions(dict):

    def __missing__(self, key):
        pos = Position(key)
        self[key] = pos
        return pos
```

**Comment by jlowin** [comment]
There's an explicit comment in the code about defaultdict semantics for Positions, so I believe this is intentional (perhaps to avoid requiring users to check if open orders have settled before querying their position dict). 

However, I do think that trying to access a key is a poor way to check if it exists (and not just because of the overhead of the `__missing__()` method). I think the more idiomatic way is:
```python
if 'SPY' in context.portfolio.positions:
    # do something
else:
    # do something else
```

**Comment by ssanderson** [comment]
It doesn't seem obviously wrong to me that doing `context.portfolio.positions['SPY']` should give back an empty position if you've never owned it, though having the defaultdict here has all kinds of unpleasant side-effects for us as code maintainers. (lots of things can add empty positions like this unexpectedly).  I'd be very happy to see all usage of defaultdict purged from zipline.

Ultimately, for performance reasons, I think positions is going to want to become a pandas object (probably a dataframe unless it only holds a single value.)  If we break this though, we should be loud about it, because it's almost certainly going to break someone's code who was relying on the defaultdict semantics.

**Comment by ehebert** [comment]
:+1: on removal of defaultdict

**Comment by dalejung** [comment]
defaultdicts are the devil. My positiontracker branch initially had it removed but took it out since it was tangential. I'll throw it back up once the refactor gets merged.

**Comment by ehebert** [comment]
Double :+1: on defaultdict removal.

**Comment by jmccorriston** [comment]
@KarenRubin I don't think this was ever fixed and I i think it should be higher up on our radar. The behavior of adding elements to the dictionary with an amount of 0 actually throws off a lot of users including several more advanced programmers.

**Comment by jbredeche** [comment]
We are fixing this on the perf branch

**Comment by jmccorriston** [comment]
Awesome!

**Comment by jmccorriston** [comment]
+1 https://secure.helpscout.net/conversation/194934629/10678/?folderId=221323

**Comment by richafrank** [comment]
Looks to be fixed.
