### ISSUE TITLE
Replace zipline's data loaders with pandas' ones.

### ISSUE THREAD

**Issue by twiecki** [quantopian/zipline#476]
There are some interesting developments on the pandas front regarding web data loaders:
* https://github.com/pydata/pandas-datareader
* https://github.com/femtotrader/pandas_datareaders_unofficial (uses requests-cache)

Ideally I'd like to remove all our own data loaders and instead instruct users to use these other ones (which include google minutely data etc). For this we'd have to change the zipline internal panel axes layout in any case (#474).

The outstanding issue is caching which I think @femtotrader's work includes but might not yet be stable enough. There are plans to integrate that into the official pandas-datareader repo eventually though.

**Comment by femtotrader** [comment]
Sorry Thomas but Google minutely data only have last days (see parameter "p").

Try for example
https://www.google.com/finance/getprices?q=AAPL&p=1d&df=cpct&ei=&auto=&f=d%2Cc%2Ch%2Cl%2Co%2Cv&i=60&x=NASD&ts=1417392000

1417392000=Mon, 01 Dec 2014 00:00:00 GMT

but we get data for 1422369000 = Tue, 27 Jan 2015 14:30:00 GMT

A way to get free minutely data could be
https://github.com/femtotrader/ig-markets-rest-api-python-library
but it can raise very quickly an API limit error `Exception: error.public-api.exceeded-account-historical-data-allowance`
Cache with requests-cache also work in this project

Some interesting links (but quite old) :
http://www.quantshare.com/sa-426-6-ways-to-download-free-intraday-and-tick-data-for-the-us-stock-market

So
http://stooq.com/db/h/
https://quantquote.com/historical-stock-data
could be solution to explore... but free minute data with a long history is something hard to find.

About Pandas DataReader, official is more "stable" than my version but doesn't support cache.

I think official DataReader should be split into one file per DataReader.

**Comment by twiecki** [comment]
Thanks @femtotrader. I'm aware of the limitation but even just some minute data could be useful. Anyway, that's not the main reason for me to embrace this but rather not replicating existing functionality.

What's the latest on merging the caching changes into the official repo?

Also, I guess your cached version is not API compatible with `pandas-datareader` ?

**Comment by femtotrader** [comment]
Yes it's not. Because I wanted DataReader to be an object... not a function (like official DataReader).

But I think that to be able to add cache to official pandas-datareader without breaking too much things, first step will be to slit code (because that's not very clean)
After this if they want to keep same API an idea could be to pass a session parameter (with session=None by default)
when no session is passed a `requests.Session` (no cache) could be create and use to performs queries. If we want to use cache we first will need to create a `requests_cache.CachedSession` which could be passed.

**Comment by ssanderson** [comment]
If we kill our own readers, we need to replace them with docs and examples of how to use the pandas official readers in a Zipline-compatible way.

**Comment by llllllllll** [comment]
We are now using pandas-datareader to load our yahoo data for the data bundles.

**Comment by Winghin2517** [comment]
Hello. I'm struggling with using the pandas datareader with google finance data. I decided to post a question on SO here: http://stackoverflow.com/questions/38466000/zipline-using-pandas-datareader-to-feed-in-google-finance-dataframe-for-non-us . Since you are now using pandas datareader to load yahoo data, is there any guidance to load google finance data in a zipline-compatible way? Yahoo Finance doesn't include my country's equities historical share prices.
