### ISSUE TITLE
Please update docs on installing from source

### ISSUE THREAD

**Issue by clivehunt** [quantopian/zipline#495]
Please add docs for one or both:
1. How to build from source.
2. I really like the idea of using a vagrant box. I used the command 'vagrant up' from a cloned zipline repository. The vagrant box went up no issues. However, after opening python and typing 'import zipline' it appears the package was not installed on the system.

Thanks

**Comment by ashleydavis** [comment]
+1

It seems almost impossible to create a functioning zipline environment. Especially so when you want to get it running from source.

**Comment by warren-oneill** [comment]
hey @ashleydavis try this https://github.com/quantopian/zipline/wiki/Development-Environment

**Comment by llllllllll** [comment]
We have a docker image for setting up a zipline env. I don't really know much about vagrant but I can look into it. Is there a particular reason that one would want to run zipline from source instead of just doing a `conda install` or `pip install`?

**Comment by JasonGiedymin** [comment]
Interestingly, I did a docker build and run. I see that the dockerfile does install freetype. When I start a container from the built image I get import errors for `%matplotlib inline`. I attached to the container for the heck of it and tried to install it. It says that it could not install it because freetype could not be built (yet I did confirm the image was successfully built which references libfreetype).

So, how about verbatim instructions on exactly how to run the dockerfile -- BUT using this jupyter running container instance to run the provided notebook in the examples folder.

I had difficulty running this repo on OSX with both virtualenv and conda. I'm not a jupyter expert but it shouldn't be this difficult (or is it!?) -- and if it isn't why isn't the docs updated with said 'simple instructions'? 🍼

**Comment by ssanderson** [comment]
@JasonGiedymin as far as I know, the OSX instructions at http://www.zipline.io/install.html#osx are up to date.  Did you run into an error trying to install following those instructions?  If so that's a bug, either in our docs or in Zipline.

w/r/t matplotlib in the docker container, we don't install it by default because Zipline by itself doesn't require matplotlib.   That's probably an oversight though, since the example notebook uses matplotlib to show output from a backtest.

**Comment by JasonGiedymin** [comment]
Ill give it another shot.

-Jason

**Comment by JasonGiedymin** [comment]
ping @ssanderson, I add a change to help new users with using this repo with docker: PR #1343

**Comment by ssanderson** [comment]
@JasonGiedymin awesome!  I'll take a look at it tonight.

**Comment by FreddieV4** [comment]
x-ref #1820 and #1823
