### ISSUE TITLE
Fix Sharpe ratio calculation

### ISSUE THREAD

**Issue by twiecki** [quantopian/zipline#853]
- [ ] Fix the zipline implementation to use risk-adjusted returns in the denominator (https://github.com/quantopian/zipline/blob/master/zipline/finance/risk/risk.py#L106) Source: http://www.pipsafe.com/Forex-E-Books/The_Sharpe_Ratio.pdf
 - [ ] Default zipline to use 1M T-Bills instead of 10Y
 - [ ] Pass in mean returns instead of cumulative returns: https://github.com/quantopian/zipline/blob/master/zipline/finance/risk/risk.py#L91 is called by https://github.com/quantopian/zipline/blob/master/zipline/finance/risk/period.py#L222 with `algorithm_period_returns` calculated by: https://github.com/quantopian/zipline/blob/master/zipline/finance/risk/period.py#L210

See https://www.quantopian.com/posts/sharpe-ratio-in-backtest-result-differs-from-than-one-in-pyfolio?utm_campaign=sharpe-ratio-in-backtest-result-differs-from-than-one-in-pyfolio&utm_medium=email&utm_source=forums for context.

**Comment by dunster** [comment]
Does this mean the "answer key" is also wrong?

**Comment by twiecki** [comment]
I'm not sure, I find it hard to navigate that. @justinlent could you help taking a look at what's going on there?

**Comment by justinlent** [comment]
Sure. Maybe I can take the answer key's daily returns and import them into pyfolio to try to figure it out

**Comment by llllllllll** [comment]
I had a conversation a couple of days ago with Jess about the risk metrics in zipline vs pyfolio. This was brought up because of the issue with information ratio that we recently found. What I would really like to do is move all of the risk metric calculations to a new project. Both pyfolio and zipline would consume this project for the risk metrics. This would mean making the risk free rate a parameter to some of these functions where I belive pyfolio currently uses 0 implicitly.

The main reason for moving this to a new repo would be to make all the risk metrics that we report consistent. We can share implementation and tests for zipline and pyfolio which is great for avoiding duplication and introducing subtle differences. I would want this to be a standalone project because I don't think it makes sense for zipline to be a dependency of pyfolio or for pyfolio to be a dependency of zipline.

**Comment by justinlent** [comment]
@llllllllll This sounds great to me.  Do you propose us waiting to migrate to the soon-to-be-developed risk module without fixing the existing bugs in zipline?  I think we should at least fix the Sharpe Ratio (and the underlying annual returns intermediate calculation), unless you think migrating to the to-be-developed module won't take that long. How long do you think it would take?

**Comment by llllllllll** [comment]
I am not sure. I don't know who will own making this change but I imagine in will need to be a joint effort from the pyfolio and zipline teams. @dunster and @richafrank, any thoughts on this?

**Comment by twiecki** [comment]
Lets move the discussion to #855.

**Comment by twiecki** [comment]
We should definitely fix it in zipline first. Sharpe is a critical statistic we use throughout. The fix also shouldn't be too difficult.

**Comment by dunster** [comment]
I think it would be a good idea to show @ehebert because he did a lot of work on the answer key in the past.  Definitely @Jstauth too.

**Comment by ehebert** [comment]
@twiecki your changes seem reasonable from an implementation stand point (and I defer to your and @justinlent's expertise on the why).

If the spreadsheet is too difficult work with, it may have outlived its usefulness, especially know that we have more experts looking at the risk calculations.
While making this fix, we could deprecate its usage (at least for Sharpe) and have the Sharpe tests in `tests.risk.test_risk_cumalitive` be checked with input defined in Python in the test suite instead of checking the answer sheet.

**Comment by ahgnaw** [comment]
https://github.com/quantopian/zipline/pull/1322
