### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by twiecki** [quantopian/zipline#894]
Some of the pegged dependencies are pretty old, like numpy 1.9.2 (now 1.11) pandas 0.16.0 (now 0.17.1), scipy 0.15.1 (now 0.16.1). These are making it harder to build conda packages as all the other packages moved ahead and numpy 1.9.2 is not being distributed anymore.

**Comment by twiecki** [comment]
CC @richafrank @llllllllll

**Comment by richafrank** [comment]
Agreed.

**Comment by ssanderson** [comment]
Note that there are several known failures in our test suite that are caused by upgrading numpy and pandas.  In particular, https://github.com/numpy/numpy/issues/6452 would require a few workarounds in the Pipeline API code, and the introduction of tz-aware datetimes in pandas 0.17.0 is likely to have implications for us.

**Comment by richafrank** [comment]
I'm going to call this closed with https://github.com/quantopian/zipline/pull/969
